package ui;

/**
 *
 * @author tharindulakshan
 */
public class DashboardUI extends javax.swing.JFrame {
    
    String userType = "";

    /**
     * Creates new form AdminHomeUI
     */
    public DashboardUI() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public DashboardUI(String ut) {
        initComponents();
        setLocationRelativeTo(null);
        userType = ut;
        
        if(userType.equals("Manager")){
            
            lblUserDashboard.setText("Manager Dashboard");
            btnUsers.setEnabled(false);
            
            
        }else if(userType.equals("Admin")){
            
            lblUserDashboard.setText("Admin Dashboard");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserDashboard = new javax.swing.JLabel();
        btnUsers = new javax.swing.JButton();
        btnCategory = new javax.swing.JButton();
        btnProducts = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnBrands = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        btnManageStock = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserDashboard.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblUserDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblUserDashboard.setText("User Dashboard");
        getContentPane().add(lblUserDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        btnUsers.setBackground(new java.awt.Color(102, 204, 0));
        btnUsers.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnUsers.setText("MANAGE USERS");
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 156, 32));

        btnCategory.setBackground(new java.awt.Color(0, 204, 204));
        btnCategory.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnCategory.setText("MANAGE CATEGORY");
        btnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 156, 32));

        btnProducts.setBackground(new java.awt.Color(0, 204, 204));
        btnProducts.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnProducts.setText("MANAGE PRODUCTS");
        btnProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductsActionPerformed(evt);
            }
        });
        getContentPane().add(btnProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, 32));

        btnLogout.setBackground(new java.awt.Color(255, 51, 51));
        btnLogout.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 309, -1, -1));

        btnBrands.setBackground(new java.awt.Color(0, 204, 204));
        btnBrands.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnBrands.setText("MANAGE BRANDS");
        btnBrands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandsActionPerformed(evt);
            }
        });
        getContentPane().add(btnBrands, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 154, 32));

        btnOrder.setBackground(new java.awt.Color(0, 204, 204));
        btnOrder.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnOrder.setText("MANAGE ORDER");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 154, 32));

        btnManageStock.setBackground(new java.awt.Color(0, 204, 204));
        btnManageStock.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnManageStock.setText("MANAGE STOCK");
        btnManageStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStockActionPerformed(evt);
            }
        });
        getContentPane().add(btnManageStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 154, 32));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dashboard Background.jpg"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
       this.setVisible(false);
       Login lp = new Login();
       lp.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed

        new ManageUser().setVisible(true);
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
        new ManageCategory().setVisible(true);
    }//GEN-LAST:event_btnCategoryActionPerformed

    private void btnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsActionPerformed
        new ManageProduct().setVisible(true);
    }//GEN-LAST:event_btnProductsActionPerformed

    private void btnBrandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandsActionPerformed
        new ManageBrand().setVisible(true);
    }//GEN-LAST:event_btnBrandsActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        new ManageOrder().setVisible(true);
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnManageStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStockActionPerformed
        new ManageStock().setVisible(true);
    }//GEN-LAST:event_btnManageStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrands;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageStock;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnProducts;
    private javax.swing.JButton btnUsers;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblUserDashboard;
    // End of variables declaration//GEN-END:variables
}
