package ui;

import classes.User;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author tharindulakshan
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        cmbUserType = new javax.swing.JComboBox<>();
        btnLogin = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblLoginIcon = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblUsername.setText("Username");
        pnl1.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 86, -1, -1));

        txtUsername.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        pnl1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 110, 281, -1));

        lblPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblPassword.setText("Password");
        pnl1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 140, -1, -1));

        txtPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        pnl1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 164, 281, -1));

        cmbUserType.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        cmbUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Manager", "Cashier" }));
        pnl1.add(cmbUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 206, 281, -1));

        btnLogin.setBackground(new java.awt.Color(0, 255, 102));
        btnLogin.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnl1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 248, 94, -1));

        btnClose.setBackground(new java.awt.Color(255, 51, 51));
        btnClose.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        pnl1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 248, 94, -1));

        lblLoginIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogicIcon.png"))); // NOI18N
        pnl1.add(lblLoginIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainBackground.jpg"))); // NOI18N
        pnl1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        if(checkEmptyFields()){
           
            User user = new User();
            user.setUserName(txtUsername.getText());
            user.setUserPassword(txtPassword.getText());
            user.setUserType(cmbUserType.getSelectedItem().toString());
        
            String userTp = user.getUserType();
            String userN = user.getUserName();
        
            if(user.userLogin()){
            
                JOptionPane.showMessageDialog(null, "WELCOME TO INVENTORY MANAGEMENT SYSTEM!","WELCOME",JOptionPane.INFORMATION_MESSAGE);
            
                if(userTp.equals("Admin") || userTp.equals("Manager")){
                    DashboardUI admin = new DashboardUI( userTp);
                    admin.setVisible(true);
                    this.setVisible(false);
                }else if(userTp.equals("Cashier")){
                    ManageOrder um = new ManageOrder();
                    um.setVisible(true);
                    this.setVisible(false);
                }
            
            }else{
                JOptionPane.showMessageDialog(null, "USER LOGIN FAILD TRY AGAIN!","ERROR",JOptionPane.ERROR_MESSAGE);
                txtUsername.setText(null);
                txtPassword.setText(null);
            
            }
            
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private boolean checkEmptyFields(){
        
        JTextField checkEmptyFilds[] = {txtUsername,txtPassword};
        
        for(JTextField txt : checkEmptyFilds){
            
            String field = txt.getText().trim();
            
            if(field.isEmpty()){
                
                JOptionPane.showMessageDialog(null, "CHECK YOUR BLANK FIELDS PLEASE!","BLANK",JOptionPane.ERROR_MESSAGE
                );
                return false;
            }
            
        }
        
        return true;
        
    }
        
        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbUserType;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblLoginIcon;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
