package ui;

/**
 *
 * @author tharindulakshan
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMainTitle = new javax.swing.JLabel();
        lblWelcomeText = new javax.swing.JLabel();
        lblLink = new javax.swing.JLabel();
        lblPhoneIcon = new javax.swing.JLabel();
        lblRobot = new javax.swing.JLabel();
        lblMainBackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMainTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblMainTitle.setText("Mobile Phone Shop");
        getContentPane().add(lblMainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        lblWelcomeText.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        lblWelcomeText.setText("WELCOME");
        getContentPane().add(lblWelcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        lblLink.setText("www.mobilephoneshop.lk");
        getContentPane().add(lblLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        lblPhoneIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/smartphone.png"))); // NOI18N
        getContentPane().add(lblPhoneIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        lblRobot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/robot1.png"))); // NOI18N
        getContentPane().add(lblRobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        lblMainBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainBackground.jpg"))); // NOI18N
        getContentPane().add(lblMainBackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        Main ms = new Main();
        ms.setVisible(true);
        
        try {
            
            Thread.sleep(300);
            new Login().setVisible(true);
            ms.dispose();
            
            
        } catch (Exception e) {
            
            System.out.println("Main Loading Error: " + e);
            
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLink;
    private javax.swing.JLabel lblMainBackgroundImage;
    private javax.swing.JLabel lblMainTitle;
    private javax.swing.JLabel lblPhoneIcon;
    private javax.swing.JLabel lblRobot;
    private javax.swing.JLabel lblWelcomeText;
    // End of variables declaration//GEN-END:variables
}
