package ui;

import classes.Admin;
import database.MyConnection;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author tharindulakshan
 */
public class ManageUser extends javax.swing.JFrame {

    /**
     * Creates new form ManageUser
     */
    public ManageUser() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageUserTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblUserPassword = new javax.swing.JLabel();
        cmbUserType = new javax.swing.JComboBox<>();
        txtSearchBar = new javax.swing.JTextField();
        cmbSearchType = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        btnUserAdd = new javax.swing.JButton();
        btnUserUpdate = new javax.swing.JButton();
        btnUserDelete = new javax.swing.JButton();
        btnUserReset = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        txtUserPassword = new javax.swing.JPasswordField();
        lblBackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblManageUserTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblManageUserTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblManageUserTitle.setText("Manage User");
        getContentPane().add(lblManageUserTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 6, -1, -1));

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "User Type"
            }
        ));
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUser);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 107, 505, 457));

        lblUserName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblUserName.setText("Username");
        getContentPane().add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 241, -1, -1));

        txtUserName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 265, 366, -1));

        lblUserPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblUserPassword.setText("Password");
        getContentPane().add(lblUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 307, -1, -1));

        cmbUserType.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        cmbUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Cashier", "Manager" }));
        getContentPane().add(cmbUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 374, 157, -1));

        txtSearchBar.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        getContentPane().add(txtSearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 107, 366, 23));

        cmbSearchType.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        cmbSearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Username", "User Type" }));
        cmbSearchType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSearchTypeActionPerformed(evt);
            }
        });
        getContentPane().add(cmbSearchType, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 136, 150, -1));

        btnSearch.setBackground(new java.awt.Color(0, 204, 204));
        btnSearch.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(871, 166, -1, -1));

        btnUserAdd.setBackground(new java.awt.Color(0, 153, 204));
        btnUserAdd.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnUserAdd.setText("Add");
        btnUserAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnUserAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 426, -1, -1));

        btnUserUpdate.setBackground(new java.awt.Color(51, 204, 0));
        btnUserUpdate.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnUserUpdate.setText("Update");
        btnUserUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUserUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 426, -1, -1));

        btnUserDelete.setBackground(new java.awt.Color(255, 102, 102));
        btnUserDelete.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnUserDelete.setText("Delete");
        btnUserDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnUserDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 426, -1, -1));

        btnUserReset.setBackground(new java.awt.Color(204, 204, 204));
        btnUserReset.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnUserReset.setText("Reset");
        btnUserReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnUserReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 426, -1, -1));

        btnClose.setBackground(new java.awt.Color(255, 51, 51));
        btnClose.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(982, 590, -1, -1));

        txtUserPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        getContentPane().add(txtUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 331, 366, -1));

        lblBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ManageUserBackground.jpg"))); // NOI18N
        getContentPane().add(lblBackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchType = cmbSearchType.getSelectedItem().toString();

        Admin search = new Admin();

        if (searchType.equals("Username")) {

            search.setUserName(txtSearchBar.getText());

            if (search.searchUser()) {
                JOptionPane.showMessageDialog(null, "USER FOUND!", "USER SEARCHING..", JOptionPane.INFORMATION_MESSAGE);
                txtUserName.setText(search.getUserName());
                txtUserPassword.setText(search.getUserPassword());
                cmbUserType.setSelectedItem(search.getUserType());

                DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
                model.setRowCount(0);

                model.addRow(new String[]{search.getUserName(), search.getUserPassword(), search.getUserType()});
            } else {
                JOptionPane.showMessageDialog(null, "USER NOT FOUND, TRY AGAIN!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } else if (searchType.equals("User Type")) {
            search.setUserType(txtSearchBar.getText());

            DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
            model.setRowCount(0);

            search.searchUserByType();

            try {

                MyConnection.rs = MyConnection.pst.executeQuery();

                while (MyConnection.rs.next()) {
                    model.addRow(new String[]{MyConnection.rs.getString(1), MyConnection.rs.getString(2), MyConnection.rs.getString(3)});

                }
                MyConnection.con.close();
                MyConnection.clear();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, "DB_SEARCH_USER_VIEW_ALL_ERROR: " + e, "USER VIEW ALL ERROR", JOptionPane.ERROR_MESSAGE);

            }

            clear();

        }

    }//GEN-LAST:event_btnSearchActionPerformed

    private void cmbSearchTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSearchTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSearchTypeActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

        viewAll();

    }//GEN-LAST:event_formComponentShown

    private void btnUserAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAddActionPerformed

        if (checkEmptyFields()) {

            Admin add = new Admin();
            add.setUserName(txtUserName.getText());
            add.setUserPassword(txtUserPassword.getText());
            add.setUserType(cmbUserType.getSelectedItem().toString());

            if (add.addUser()) {
                JOptionPane.showMessageDialog(null, "NEW USER ADDED!", "NEW USER", JOptionPane.INFORMATION_MESSAGE);
            } else {

                JOptionPane.showMessageDialog(null, "USER NOT INSERTED, TRY AGAIN!", "ERROR", JOptionPane.ERROR_MESSAGE);

            }

            viewAll();
            clear();
            btnUserUpdate.setEnabled(false);

        } else {
            txtUserName.setText(null);
            txtUserPassword.setText(null);
        }


    }//GEN-LAST:event_btnUserAddActionPerformed

    private void btnUserUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserUpdateActionPerformed
        Admin update = new Admin();
        update.setUserName(txtUserName.getText());
        update.setUserPassword(txtUserPassword.getText());
        update.setUserType(cmbUserType.getSelectedItem().toString());

        if (update.updateUser()) {
            JOptionPane.showMessageDialog(null, "USER UPDATED!", "USER UPDATE", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "USER NOT UPDATED, TRY AGAIN!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        viewAll();
    }//GEN-LAST:event_btnUserUpdateActionPerformed

    private void btnUserDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDeleteActionPerformed
        
        Admin delete = new Admin();
        delete.setUserName(txtUserName.getText());

        if (delete.deleteUser()) {
            JOptionPane.showMessageDialog(null, "USER DELETED!", "USER DELETE", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "USER NOT DELETED, CHECK YOUR FIELDS AND TRY AGAIN!", "NOT FOUND!", JOptionPane.ERROR_MESSAGE);
        }

        viewAll();
        clear();
    }//GEN-LAST:event_btnUserDeleteActionPerformed

    private void btnUserResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserResetActionPerformed
        txtSearchBar.setText(null);
        txtUserName.setText(null);
        txtUserPassword.setText(null);
        viewAll();
        btnUserAdd.setEnabled(true);
    }//GEN-LAST:event_btnUserResetActionPerformed

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        int index = tblUser.getSelectedRow();
        TableModel model = tblUser.getModel();

        String userName = model.getValueAt(index, 0).toString();
        txtUserName.setText(userName);

        String password = model.getValueAt(index, 1).toString();
        txtUserPassword.setText(password);

        String userType = model.getValueAt(index, 2).toString();
        cmbUserType.setSelectedItem(userType);

        btnUserAdd.setEnabled(false);
        btnUserUpdate.setEnabled(true);


    }//GEN-LAST:event_tblUserMouseClicked

    private void viewAll() {

        DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
        model.setRowCount(0);

        Admin admin = new Admin();
        admin.viewAll();

        try {

            MyConnection.rs = MyConnection.pst.executeQuery();

            while (MyConnection.rs.next()) {
                model.addRow(new String[]{MyConnection.rs.getString(1), MyConnection.rs.getString(2), MyConnection.rs.getString(3)});

            }
            MyConnection.con.close();
            MyConnection.clear();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "DB_USER_VIEW_ALL_ERROR: " + e, "USER VIEW ALL ERROR", JOptionPane.ERROR_MESSAGE);

        }

    }

    private void clear() {

        txtSearchBar.setText(null);
        txtUserName.setText(null);
        txtUserPassword.setText(null);

    }

    private boolean checkEmptyFields() {

        JTextField checkEmptyFilds[] = {txtUserName, txtUserPassword};

        for (JTextField txt : checkEmptyFilds) {

            String field = txt.getText().trim();

            if (field.isEmpty()) {

                JOptionPane.showMessageDialog(null, "CHECK YOUR BLANK FIELDS PLEASE!", "BLANK", JOptionPane.ERROR_MESSAGE
                );
                return false;
            }

        }

        return true;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUserAdd;
    private javax.swing.JButton btnUserDelete;
    private javax.swing.JButton btnUserReset;
    private javax.swing.JButton btnUserUpdate;
    private javax.swing.JComboBox<String> cmbSearchType;
    private javax.swing.JComboBox<String> cmbUserType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackgroundImage;
    private javax.swing.JLabel lblManageUserTitle;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserPassword;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtSearchBar;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPasswordField txtUserPassword;
    // End of variables declaration//GEN-END:variables
}
